title: E-Learning
author:
  name: E-Robot
  email: erobotkh@gmail.com
description: >-
  Documents & Learning materials by E-Robot
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: facebook, user_url: "https://web.facebook.com/ERobotKH" }
    - { platform: github, user_url: "https://github.com/erobotkh" }
    - { platform: linkedin, user_url: "https://linkedin.com/company/erobotkh" }
    - { platform: telegram, user_url: "https://t.me/erobot_generalknowledge" }
    - { platform: youtube, user_url: "https://www.youtube.com/@erobotkh" }

header_pages:
  # - about.md

show_excerpts: false

exclude:
  - _posts/2023-02-05-sample.md
  - about.md
  - vendor
